<?php
/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PagarmeCoreApiLib\Tests;

use PagarmeCoreApiLib\APIException;
use PagarmeCoreApiLib\Exceptions;
use PagarmeCoreApiLib\APIHelper;
use PagarmeCoreApiLib\Models;
use PagarmeCoreApiLib\Utils\DateTimeHelper;

class ChargesControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \PagarmeCoreApiLib\Controllers\ChargesController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass()
    {
        $client = new \PagarmeCoreApiLib\PagarmeCoreApiClient();
        self::$controller = $client->getCharges();
    }

    /**
     * Setup test
     */
    protected function setUp()
    {
        $this->httpResponse = new HttpCallBackCatcher();
    }

    /**
     * Lists all charges
     */
    public function testTestGetCharges()
    {
        // Parameters for the API call
        $page = null;
        $size = null;
        $code = null;
        $status = null;
        $paymentMethod = null;
        $customerId = null;
        $orderId = null;
        $createdSince = null;
        $createdUntil = null;

        // Set callback and perform API call
        $result = null;
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            $result = self::$controller->getCharges($page, $size, $code, $status, $paymentMethod, $customerId, $orderId, $createdSince, $createdUntil);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );

        // Test headers
        $headers = [];
        $headers['Content-Type'] = 'application/json' ;
        
        $this->assertTrue(
            TestHelper::areHeadersProperSubsetOf($headers, $this->httpResponse->getResponse()->getHeaders(), true),
            "Headers do not match"
        );
    }
}
