<?php
/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PagarmeCoreApiLib\Models;

use JsonSerializable;

/**
 *Request for canceling a subscription
 */
class CreateCancelSubscriptionRequest implements JsonSerializable
{
    /**
     * Indicates if the pending invoices must also be canceled.
     * @required
     * @maps cancel_pending_invoices
     * @var bool $cancelPendingInvoices public property
     */
    public $cancelPendingInvoices;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool $cancelPendingInvoices Initialization value for $this->cancelPendingInvoices
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->cancelPendingInvoices = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['cancel_pending_invoices'] = $this->cancelPendingInvoices;

        return $json;
    }
}
